# Dependencies
markdown: redcarpet
highlighter: pygments

# Permalinks
permalink: pretty
relative_permalinks: true

# Setup
title: "Andrea Hu's Blog"
tagline: 'Handy Andy, does it all!'
description: 'Your friendly tech support neighbor.'
url: http://hyde.getpoole.com
baseurl: /

author:
  name: 'Andrea Hu'
  url: https://twitter.com/mdo

paginate: 5

# Custom vars
version: 2.1.0

github:
  repo: https://github.com/AndreaHu3299/AndreaHu3299.github.io
